apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakF5TURVdwpOek01TlRkYUZ3MDBOakF5TURVd056TTVOVGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDL2dkWkhmRjNiMnZhbUxrTU10Rk0zdDhYT25kNWNxMk13VnlEWXpBQWs2bkRCeUFYSQpXRE14c0k2M3JaNmt3SGllcXZuUjRvQVZyWmhUYjdySExMWk5xK3NTSDNndG1tbTBOT09ta0xuRW5ROEw5RmJpCmtCVmkrVDlQbU54WHFCNnE1VUMzSUNTT1JoWVBSZjR6WXdDSTVPVE5OTzh1UFpGOGg4bXc5OHNoZWpNUE1oOXoKMmxzZHRHV2N2Y0UyVG1qQ0lpMCsvYlI1Y1Q0eVpoOHpGeWpMVFJHRTRwSzZxT21HNkk0OHJBVnhxNkFHaGEySApHOEZqQ0RHbHpQcWpDODFIcGRCazJWQVVFMDdza1RjUk56Z0daWGxOKzNrWllQUnpPcFJoRUMvQStyZ21vc0ZECnFQNGhXSkF6ZjFLUkNEdS95Ym9QZ1NybHREY2VVbXp0TlR2TEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNlM2IvbG5YcWgwc2xzYWU2TQovdXZXK2RYb2p6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFlNGhWdW5vYjNocUZaeG5oZHd0NTFuWXZYNTk2Ck9MV2NPdGhoY2l6SlFadnlKSXFRNHhJSm9UQk9DV3lkSk5VZUxLRUdxL21GdzBrcnA5NGxuU3NFeXUzTEpWRmYKYWVXVXR4SzNvR3R2UDVuQXdJWlI4MEZ2ZlUxUEFpMUxBWlRIMW0wM2FXaHBjMkZpdko4emJTLzRabzRzN2ZwKwpSL2daTlg4YnlOaDFGSzlUNXJSaTNnbWVmZUFHaS82dmNLcmwxK25ZYlpEU1VHL01xTDZReitncURjMGFkcUFOCnQzdDZLVmZSOFZ6RVRtV2hNQnZVOVJKZWYyQ2tXUjVPeExNbVBwY0J6VUlOakNRS3R6ZmluVHlDZmNPeW1hOUIKQTEvdjlsc04yWkJaZS82TGpLR1V6VGs3endmUk43SUVRRy9jOFdQUm00MWhhZmw1MGRyZTRwT0JzZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://bb5d69d6-625b-4c2e-b8b7-70bb6c895f7a.k8s.ondigitalocean.com
  name: do-nyc1-todo-cluster
contexts:
- context:
    cluster: do-nyc1-todo-cluster
    user: do-nyc1-todo-cluster-admin
  name: do-nyc1-todo-cluster
current-context: do-nyc1-todo-cluster
kind: Config
preferences: {}
users:
- name: do-nyc1-todo-cluster-admin
  user:
    token: dop_v1_3df874f04f6401ee4b389eb3901f1432d93b68b7252865d479672517b84b802d
